import { StyleSheet } from "react-native";

export const landingStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#ffffff',
    },
    contentWrapper: {
      flex: 1,
      paddingHorizontal: 24,
      paddingVertical: 32,
      justifyContent: 'space-between',
    },
    headerSection: {
      alignItems: 'center',
      marginTop: 16,
    },
    iconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(6, 182, 212, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      borderWidth: 1,
      borderColor: 'rgba(6, 182, 212, 0.2)',
    },
    lightningIcon: {
      fontSize: 28,
      color: '#06b6d4',
    },
    appTitle: {
      fontSize: 40,
      fontWeight: '600',
      letterSpacing: 1,
      marginBottom: 8,
    },
    appTitleFirst: {
      color: '#06b6d4',
    },
    appTitleSecond: {
      color: '#0891b2',
    },
    tagline: {
      fontSize: 16,
      color: '#64748b',
      letterSpacing: 0.5,
      fontWeight: '400',
    },
    mainContent: {
      flex: 1,
      justifyContent: 'center',
      marginVertical: 24,
    },
    contentCard: {
      backgroundColor: '#ffffff',
      borderRadius: 24,
      padding: 28,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    heroTitle: {
      fontSize: 28,
      fontWeight: '700',
      color: '#0f172a',
      textAlign: 'center',
      lineHeight: 34,
      marginBottom: 16,
      letterSpacing: 0.5,
    },
    heroSubtitle: {
      fontSize: 16,
      color: '#64748b',
      textAlign: 'center',
      marginBottom: 32,
      fontWeight: '400',
    },
    featuresContainer: {
      alignItems: 'center',
      marginBottom: 32,
      width: '100%',
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: 'rgba(6, 182, 212, 0.05)',
      borderRadius: 16,
      width: '100%',
      maxWidth: 240,
      borderWidth: 1,
      borderColor: 'rgba(6, 182, 212, 0.1)',
    },
    featureIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(6, 182, 212, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    featureIcon: {
      fontSize: 16,
      color: '#06b6d4',
    },
    featureText: {
      fontSize: 15,
      color: '#334155',
      fontWeight: '500',
      letterSpacing: 0.3,
    },
    progressSection: {
      alignItems: 'center',
      marginTop: 16,
    },
    progressCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      borderWidth: 4,
      borderColor: '#06b6d4',
      backgroundColor: 'rgba(6, 182, 212, 0.05)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    progressText: {
      color: '#06b6d4',
      fontSize: 20,
      fontWeight: '700',
    },
    progressLabel: {
      color: '#64748b',
      fontSize: 14,
      fontWeight: '500',
    },
    actionContainer: {
      paddingHorizontal: 8,
      paddingBottom: 16,
    },
    primaryButton: {
      borderRadius: 16,
      marginBottom: 12,
      shadowColor: '#06b6d4',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    buttonGradient: {
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 16,
      alignItems: 'center',
    },
    primaryButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.5,
    }
  });